# Generated by Django 4.0.5 on 2022-07-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_remove_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='User',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
