# Generated by Django 4.0.5 on 2022-07-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_remove_post_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
