# Generated by Django 4.0.5 on 2022-07-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_rename_post_comment_post_rename_text_comment_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='User',
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
