# Generated by Django 4.0.6 on 2022-07-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_remove_post_wcount_post_view_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tag', models.CharField(max_length=100)),
                ('post', models.ManyToManyField(to='myblog.post')),
            ],
        ),
    ]
