# Generated by Django 4.0.6 on 2022-07-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
