# Generated by Django 4.0.5 on 2022-07-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_category_post_image_comment_post_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Comments',
        ),
    ]
